### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by harrywang** [inkjet/flask-aws-tutorial#1]
I have to change Flask-SQLAlchemy==2.0 to Flask-SQLAlchemy==1.0 to make pip install work

**Comment by inkjet** [comment]
Interesting. What version Python are you running?  I am using 2.7.6 in a virtual environment, and the requirements file worked fine for me.

**Comment by harrywang** [comment]
2.7.8

**Comment by inkjet** [comment]
Hmm, I'm unable to replicate the error under 2.7.8 -- Flask-SQLAlchemy 2.0 is installing fine for me. Maybe you can open a bug on their [GitHub repo](https://github.com/mitsuhiko/flask-sqlalchemy)?  

Did the demo work okay with 1.0?

**Comment by harrywang** [comment]
I restarted my macbook and the installation works. I have no idea why it did not work previously.

**Comment by Parkman328** [comment]
the pip install fails on python 3.7
