### ISSUE TITLE
Db table not created

### ISSUE THREAD

**Issue by harrywang** [inkjet/flask-aws-tutorial#2]
I added the following to config.py 

`import os`
`basedir = os.path.abspath(os.path.dirname(__file__))`
`# Uncomment the line below if you want to work with a local DB`
`SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir, 'data-dev.sqlite')`

and run
`$ python db_create.py`

the database file is created but no table is created.

**Comment by inkjet** [comment]
I found the same bug yesterday and modified `db_create.py` to ensure tables are created.  Let me know if you get the same issue once you update your repo.

**Comment by harrywang** [comment]
problem solved after pulling your update. Thanks!!
